[package]
name = "photo_culler"
version = "0.1.0"
edition = "2024"

[package.metadata.packager]
product-name = "Photo Culler"
identifier = "com.photo-culler.app"
authors = ["Luuk"]
description = "A photo culling application"

[dependencies]
appdirs = "0.2.0"
byteorder = "1.5.0"
crossbeam = "0.8.4"
image = "0.25.9"
kamadak-exif = "0.6.1"
rsraw = "0.1.1"
serde = "1.0.228"
serde_json = "1.0.149"
slint = "1.15"
thiserror = "2.0.18"


[build-dependencies]
slint-build = "1.15"
