import { ScrollView } from "std-widgets.slint";
import { Theme } from "theme.slint";

export component Filmstrip inherits Rectangle {
    in property <[image]> images;
    in property <[int]> statuses;
    in property <[bool]> is_shown;
    in property <[int]> visible_indices;
    in-out property <int> selected-index;

    changed selected-index => {
        root.update-scroll();
    }

    callback select-photo(int);

    height: 120px;
    background: #181818;
    border-width: 1px;
    border-color: #333;

    public function update-scroll() {
        if (root.visible_indices.length > root.selected-index && root.visible_indices[root.selected-index] != -1) {
            filmstripView.viewport-x = (filmstripView.width / 2) - (root.visible_indices[root.selected-index] * 108px) - 60px;
        }
    }

    filmstripView := ScrollView {
        width: 100%;

        animate viewport-x {
            duration: 200ms;
            easing: ease-out;
        }

        HorizontalLayout {
            spacing: 0px;
            padding: 10px;

            for image[i] in root.images: Rectangle {
                width: is_shown[i] ? 108px : 0px;
                height: 100px;
                visible: is_shown[i];
                clip: true;

                Rectangle {
                    x: 4px;
                    width: 100px;
                    height: 100px;
                    background: #2a2a2a;
                    border-radius: 4px;
                    border-width: 2px;
                    border-color: i == root.selected-index ? Theme.accent : transparent;
                    clip: true;

                    Image {
                        source: image;
                        width: 100%;
                        height: 100%;
                        image-fit: cover;
                    }

                    if (i == root.selected-index): Rectangle {
                        border-width: 2px;
                        border-color: Theme.accent;
                    }

                    if (root.statuses[i] != 0): Rectangle {
                        x: parent.width - 16px;
                        y: 4px;
                        width: 12px;
                        height: 12px;
                        border-radius: 6px;
                        background: root.statuses[i] == 1 ? Theme.success : Theme.danger;
                        border-width: 1px;
                        border-color: white;
                    }
                }

                TouchArea {
                    clicked => {
                        root.selected-index = i;
                        root.update-scroll();
                        root.select-photo(i);
                    }
                }
            }
        }
    }
}
